spring:
  data:
    mongodb:
      uri: {URI}
      database: journaldb
      auto-index-creation: true

  main:
    allow-circular-references: true

server:
  port: 8085
#  servlet:
#    context-path: /journal

