spring:
  data:
    redis:
      uri:redis://default:4ihokwMYvnbVJRIkvGpDaKvHsH6gGhfh@redis-15575.c264.ap-south-1-1.ec2.redns.redis-cloud.com:15575
    #    host: localhost
    #    port: 6379
    mongodb:
      uri: mongodb+srv://vdhinithya:HLNdVq4NJNzM6Udc@cluster0.3cbzl.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true

  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: vdhinithya@gmail.com
    password: wouichdqkkqhzfzj

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
#  servlet:
#    context-path: // now this has to be there after http://localhost:8080, like http://localhost:8080/journal/api/jobs

#logging:
#  level:
#    com:
#      dhinithya:
#        journalApp: DEBUG

weather:
  api:
    key: b5ca7f37fbd0da973df8638c66bf1efc
# can be used like this
# weather_api_key: b5ca7f37fbd0da973df8638c66bf1efc