spring:
  data:
    mongodb:
      uri: {URI}
      database: journaldb
      auto-index-creation: true

  main:
    allow-circular-references: true

server:
  port: 8080
#  servlet:
#    context-path: // now this has to be there after http://localhost:8080, like http://localhost:8080/journal/api/jobs

#logging:
#  level:
#    com:
#      dhinithya:
#        journalApp: DEBUG
